'use client'

import { type ReactNode, useCallback, useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { motion, AnimatePresence } from 'framer-motion'
import { ArrowLeft, Play, Clock, Download, Eye, EyeOff, Keyboard } from 'lucide-react'
import { AiTutor } from '@/components/ai-tutor'
import { AchievementsPanel, emitAchievement } from '@/components/achievements-panel'
import { NoiseBackground } from '@/components/ui/noise-background'
import { ThemeToggle } from '@/components/theme-toggle'

import { unlockAchievement, getAchievements } from '@/lib/achievements'
import type { Subject } from '@/lib/subjects'
import { cn } from '@/lib/utils'

interface LabShellProps {
  subject: Subject
  started: boolean
  onStart: () => void
  greeting: string
  getState: () => string
  controls: ReactNode
  stage: ReactNode
  readouts: ReactNode
  onAchievementUnlock?: () => void
}

function formatTime(seconds: number) {
  const m = Math.floor(seconds / 60).toString().padStart(2, '0')
  const s = (seconds % 60).toString().padStart(2, '0')
  return `${m}:${s}`
}

export function LabShell({
  subject,
  started,
  onStart,
  greeting,
  getState,
  controls,
  stage,
  readouts,
}: LabShellProps) {
  const [highContrast, setHighContrast] = useState(false)
  const [showKeys, setShowKeys] = useState(false)
  const [elapsed, setElapsed] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const getStateRef = useRef(getState)
  getStateRef.current = getState

  // Session timer
  useEffect(() => {
    if (!started) return
    timerRef.current = setInterval(() => setElapsed((e) => e + 1), 1000)
    return () => { if (timerRef.current) clearInterval(timerRef.current) }
  }, [started])

  // First experiment achievement
  useEffect(() => {
    if (started) {
      const wasNew = unlockAchievement('first_experiment')
      if (wasNew) {
        const a = getAchievements().find((x) => x.id === 'first_experiment')
        if (a) emitAchievement({ ...a, unlocked: true })
      }
    }
  }, [started])

  // Keyboard shortcuts
  useEffect(() => {
    if (!started) return
    function onKey(e: KeyboardEvent) {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return
      // Space and R are handled by individual labs via their own key bindings
      if (e.key === '?') setShowKeys((v) => !v)
      if (e.key === 'a' || e.key === 'A') setHighContrast((v) => !v)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [started])

  // Accessibility toggle achievement
  function toggleContrast() {
    setHighContrast((v) => {
      if (!v) {
        const wasNew = unlockAchievement('accessibility_ally')
        if (wasNew) {
          const a = getAchievements().find((x) => x.id === 'accessibility_ally')
          if (a) emitAchievement({ ...a, unlocked: true })
        }
      }
      return !v
    })
  }

  // Export experiment summary
  const exportSummary = useCallback(() => {
    const state = getStateRef.current()
    const lines = [
      `SciSim Lab Report`,
      `==================`,
      `Subject: ${subject.tag} — ${subject.title}`,
      `Date: ${new Date().toLocaleString()}`,
      `Session Duration: ${formatTime(elapsed)}`,
      ``,
      `Live Simulation State:`,
      state,
      ``,
      `Generated by SciSim — Interactive STEM Education`,
    ]
    const text = lines.join('\n')
    navigator.clipboard.writeText(text).then(() => {
      // Could show a mini toast — keep it simple
    }).catch(() => {
      const el = document.createElement('textarea')
      el.value = text
      document.body.appendChild(el)
      el.select()
      document.execCommand('copy')
      document.body.removeChild(el)
    })
  }, [subject, elapsed])

  return (
    <main
      className={cn(
        'lab-stage min-h-screen bg-background text-foreground',
        highContrast && 'high-contrast',
      )}
    >
      <AchievementsPanel highContrast={highContrast} />

      <div className="mx-auto w-full max-w-[1600px] px-4 py-5 md:px-6">
        {/* header */}
        <header className="flex items-center justify-between gap-3">
          <Link
            href="/lab"
            className="inline-flex items-center gap-2 rounded-xl border border-border bg-card/60 px-4 py-2.5 font-mono text-xs uppercase tracking-[0.2em] text-foreground backdrop-blur transition hover:bg-card"
          >
            <ArrowLeft className="size-3.5" />
            Lab
          </Link>

          {/* Center: timer */}
          {started && (
            <div className="flex items-center gap-1.5 rounded-xl border border-border bg-card/60 px-3 py-2 backdrop-blur">
              <Clock className="size-3 text-muted-foreground" />
              <span className="font-mono text-xs tabular-nums text-muted-foreground" aria-label="Session time">
                {formatTime(elapsed)}
              </span>
            </div>
          )}

          <div className="flex items-center gap-2">
            {/* Theme Toggle */}
            <ThemeToggle />

            {/* Accessibility toggle */}
            <button
              onClick={toggleContrast}
              title={highContrast ? 'Disable high contrast (A)' : 'Enable high contrast (A)'}
              aria-label="Toggle accessibility mode"
              className="grid size-9 place-items-center rounded-xl border border-border bg-card/60 text-muted-foreground backdrop-blur transition hover:bg-card hover:text-foreground"
            >
              {highContrast ? <Eye className="size-4" /> : <EyeOff className="size-4" />}
            </button>

            {/* Export */}
            {started && (
              <button
                onClick={exportSummary}
                title="Copy experiment summary to clipboard"
                aria-label="Export experiment summary"
                className="grid size-9 place-items-center rounded-xl border border-border bg-card/60 text-muted-foreground backdrop-blur transition hover:bg-card hover:text-foreground"
              >
                <Download className="size-4" />
              </button>
            )}

            {/* Keyboard help */}
            <button
              onClick={() => setShowKeys((v) => !v)}
              title="Keyboard shortcuts (?)"
              aria-label="Keyboard shortcuts"
              className="grid size-9 place-items-center rounded-xl border border-border bg-card/60 text-muted-foreground backdrop-blur transition hover:bg-card hover:text-foreground"
            >
              <Keyboard className="size-4" />
            </button>

            <div className="text-right">
              <p
                className="font-mono text-xs uppercase tracking-[0.25em]"
                style={{ color: subject.accentVar }}
              >
                {subject.index} / {subject.tag}
              </p>
              <h1 className="text-lg font-semibold tracking-tight md:text-xl">
                {subject.title}
              </h1>
            </div>
          </div>
        </header>

        {/* Keyboard shortcuts popup */}
        <AnimatePresence>
          {showKeys && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              className="mt-3 rounded-xl border border-border bg-card/80 px-4 py-3 backdrop-blur"
            >
              <p className="mb-2 font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Keyboard Shortcuts</p>
              <div className="grid grid-cols-2 gap-x-8 gap-y-1 font-mono text-xs text-muted-foreground sm:grid-cols-4">
                <span><kbd className="rounded bg-secondary px-1">Space</kbd> Pause/Play</span>
                <span><kbd className="rounded bg-secondary px-1">R</kbd> Reset</span>
                <span><kbd className="rounded bg-secondary px-1">A</kbd> Accessibility</span>
                <span><kbd className="rounded bg-secondary px-1">?</kbd> Shortcuts</span>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_420px]">
          {/* stage + controls */}
          <div className="flex flex-col gap-5">
            <div className={cn(
              'relative overflow-hidden rounded-2xl border border-border bg-card/50 lg:sticky lg:top-5 z-20',
              highContrast && 'border-2 border-foreground/30',
            )}>
              <div className="relative aspect-[16/11] w-full md:aspect-[16/9]">
                {stage}
              </div>

              {!started && (
                <motion.div
                  initial={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-5 bg-background/70 backdrop-blur-md"
                >
                  <div className="text-center">
                    <p
                      className="font-mono text-xs uppercase tracking-[0.3em]"
                      style={{ color: subject.accentVar }}
                    >
                      {subject.tag} Experiment
                    </p>
                    <h2 className="mt-2 text-2xl font-semibold tracking-tight">
                      {subject.title}
                    </h2>
                    <p className="mt-2 max-w-xs text-sm text-muted-foreground">
                      An AI tutor will guide you in real time
                    </p>
                  </div>
                  <NoiseBackground
                    containerClassName="rounded-full"
                    gradientColors={[
                      `color-mix(in oklch, ${subject.accentVar} 80%, transparent)`,
                      subject.accentVar,
                    ]}
                  >
                    <button
                      onClick={onStart}
                      className="relative z-10 inline-flex items-center gap-2 rounded-full px-6 py-3 font-medium text-white shadow-lg transition hover:brightness-110 active:scale-95"
                      style={{ backgroundColor: subject.accentVar }}
                    >
                      <Play className="size-4 fill-current" />
                      Start Experiment
                    </button>
                  </NoiseBackground>
                </motion.div>
              )}


              {/* live readouts overlay */}
              <div className="pointer-events-none absolute inset-x-0 bottom-0 p-3 md:p-4" aria-live="polite">
                {readouts}
              </div>
            </div>

            <div className={cn(
              'rounded-2xl border border-border bg-card/50 p-4 md:p-5 relative z-10',
              highContrast && 'border-2 border-foreground/20',
            )}>
              {controls}
            </div>
          </div>

          {/* tutor */}
          <div className="h-[600px] lg:h-[calc(100vh-120px)] lg:sticky lg:top-5 z-20">
            <AiTutor
              subject={subject.id}
              greeting={greeting}
              getState={getState}
              enabled={started}
              highContrast={highContrast}
            />
          </div>
        </div>
      </div>
    </main>
  )
}
